### ISSUE TITLE
Disable ability to view others' submissions in contest, even if you have solved the problem

### ISSUE THREAD

**Issue by FatalEagle** [DMOJ/site#249] opened 2015-09-17 21:09 UTC
Why is this even a thing?

**Comment by Xyene** [comment] 2015-09-17 21:12
Because there's no extra logic implemented to disable it, and it's necessary for hacks in the long run?

**Comment by FatalEagle** [comment] 2015-09-17 23:46
Right, but a user can resubmit "correct" code to prepare for rejudge (if they pass with wrong solution). That is not good.

**Comment by Xyene** [comment] 2015-09-17 23:55
But that's just a case of cheating. Anyways, this would require some sort of "submission locking" feature.

**Comment by FatalEagle** [comment] 2015-09-17 23:57
Yes, it's cheating. People can cheat right now. They can see others' submissions, and resubmit with their idea. It's just bad to be able to see submissions during a live contest.

**Comment by quantum5** [comment] 2015-12-14 18:29
Isn't this a duplicate of #301?

**Closed by quantum5** 2015-12-14 18:29 UTC
Labels: contest, duplicate, enhancement
