### ISSUE TITLE
Anonymous User Submissions

### ISSUE THREAD

**Issue by FatalEagle** [DMOJ/site#76] opened 2015-03-27 01:08 UTC
Allow people who are not registered to submit. A lot of potential users could turn away from the judge just because it's such a hassle to go through registration. Existing users would also be able to use this feature, as users who already want to submit away from their main account can just create a new account, which ends up as more garbage on the site. Limits may be imposed on this feature to prevent abuse.

**Comment by quantum5** [comment] 2015-03-27 01:09
Duplicate of #17

**Comment by Xyene** [comment] 2015-03-27 01:11
@quantum5 incorrect; #17 refers to registered users submitting anonymously, this refers to unregistered users testing out the site.

**Comment by FatalEagle** [comment] 2015-03-27 01:11
I mentioned both interpretations just to be safe.

**Comment by quantum5** [comment] 2015-03-27 01:12
@Xyene the issues are rather similar. #17 is more of a subset of this issue.

**Comment by Xyene** [comment] 2015-03-27 01:16
@quantum5 in implementation, hardly. #17 can easily be achieved by having an `anonymous` boolean field in the Submission model, while this can't.

If we do allow unregistered users to test out the site functionality, we should have banners reminding them to register an account on all relevant pages (submit/view source/view status). And to tell them that they can trial the site functionality, we should have a message stating as much on the main page. Preferably bold. And obtrusive so that they notice it in the first place.

**Comment by quantum5** [comment] 2015-03-27 01:19
This can't really be implemented nicely. Implementation of this results rippling effects over the entire site. First of all there will be no way to identify such submissions, and it has significant problems regarding rankings. Not to say that changing a basic model `Submission` in a non-trivial way will break most of the site.

**Comment by FatalEagle** [comment] 2015-03-27 01:22
The submissions can be identified just like any other submission, except it is assigned to a user named "anonymous". "anonymous" can be explicitly excluded from the rankings.

**Comment by quantum5** [comment] 2015-03-27 01:25
Or simply: "to try the site, login as the user anonymous with the password anonymous".

**Comment by Xyene** [comment] 2015-03-27 01:29
And next we'll have anonymous' user profile show the Guy Fawkes mask as its Gravatar. Having an anonymous user for people to do things on sounds like a bad idea - we'd have to explicitly disallow profile editing, commenting and all.

**Comment by FatalEagle** [comment] 2015-03-27 01:30
@quantum5 It's such a hassle to login though. Also anonymous would need "submit without limit".

**Comment by quantum5** [comment] 2015-03-27 01:39
Adding anonymous usage is the same as having an anonymous user except more difficult. Also, submit without limit makes it exceptionally prone to abuse.

**Comment by FatalEagle** [comment] 2015-03-27 01:40
I mean if users had to log on to the account that account would need to be muted and have submit without limit.

**Comment by quantum5** [comment] 2015-03-27 01:54
May be we can have a codecha AND a survey to prevent abuse lol. But the implementation is pretty painful. We probably won't need this anyway when registration is made painless as in #50.

**Comment by Xyene** [comment] 2015-03-27 01:56
I'd quote a certain brilliant amusement park manager, but I forgot what it was exactly that he said. Paraphrased, something along the lines of "every new, returning user registration is worth the effort".

**Comment by Xyene** [comment] 2015-03-27 01:57
Certainly once #50 is in this shouldn't be a high-priority issue, but it would be worthwhile to have once we have the time to implement it.

**Comment by FatalEagle** [comment] 2015-03-27 02:00
Relevant: http://screencloud.net/v/jALV

**Comment by Xyene** [comment] 2015-03-27 02:03
That's the one.

**Comment by quantum5** [comment] 2015-03-27 02:04
MY EYES.

**Comment by Xyene** [comment] 2017-02-22 09:10
The registration form really is a breeze to go through now.

**Closed by Xyene** 2017-02-22 09:10 UTC
Labels: feature
