### ISSUE TITLE
Better message queue

### ISSUE THREAD

**Issue by Xyene** [DMOJ/site#183] opened 2015-05-24 20:04 UTC
`event_socket_server` has served us well, but is so unmaintainable that we should do ourselves the favour of removing it. The current messaging framework dates back to the first hours of the DMOJ judge, and hasn't evolved much since then. Given our current scale, we should cut `event_socket_server` out and replace it with an enterprise-ready solution like [RabbitMQ](http://www.squaremobius.net/rabbit.js/). 

At the very least, it would demystify judge-bridge interactions (RabbitMQ works well with metrics/monitoring), and would remove the risk from any hidden bugs `event_socket_server` may still have.

[It also plays nice with node.js](http://www.squaremobius.net/rabbit.js/).

**Comment by quantum5** [comment] 2015-05-24 23:03
`event_socket_server` has so many potential gotchas that I don't even remember how to use it correctly. It also has bugs as seen in #5 that can not actually even be reproduced.

**Comment by Xyene** [comment] 2015-05-24 23:51
This would also positively affect https://github.com/DMOJ/hephaestus

**Comment by quantum5** [comment] 2015-05-25 01:36
Design:

* A `node.js` server which async queries MySQL for authentication.
* RabbitMQ server to handle judge connections.
* Django client connects to RabbitMQ and sends submission requests as messages.
* Judges will receive the message, and if it can be handled, acknowledge, otherwise reject. RabbitMQ will dispatch to another judge.
* Judges will routinely send a ping message to the site, and a django loaded worker will process the pings. Failure to ping means marking as offline. Judges will track their own uptime. Ping round trip and clock difference will probably be broken unless RabbitMQ actually has received time
* Judges will report their capabilities (languages, problems) so the site knows what to show on the interface
* Judges will report submission results to to the site, processed by the same processor as above, to update database
* Judges will report identity, and identity is stored with the submission
* If a judge has a submission and doesn't ping, that submission IEs
* If a judge pings with a different startup time, its submissions IE
* Abortion requests will be handled as broadcast

**Comment by quantum5** [comment] 2015-05-25 01:38
And I also believe the websocket server can use a RabbitMQ instead of an internal queue. This would allow it to scale.

**Comment by Xyene** [comment] 2015-05-25 01:40
* Judge authentication will be handled by [RabbitMQ](http://www.rabbitmq.com/blog/2011/02/07/who-are-you-authentication-and-authorisation-in-rabbitmq-231/). The Django client can use a public auth key.

**Comment by quantum5** [comment] 2015-05-25 02:41
https://github.com/rabbitmq/rabbitmq-auth-backend-http can cover for authentication. Django will just reply over HTTP.

**Comment by quantum5** [comment] 2015-05-29 23:23
>* Judges will report identity, and identity is stored with the submission
>* If a judge has a submission and doesn't ping, that submission IEs
>* If a judge pings with a different startup time, its submissions IE

Was thinking too hard. We can actually simply acknowledge the submission after it's done, and failure to do so will cause RabbitMQ to automagically redispatch it. All we really need to do is clear all test cases and remove error messages when the `P` state is entered.

**Comment by quantum5** [comment] 2015-05-30 23:49
https://github.com/rabbitmq/rabbitmq-auth-backend-http can be configured alongside the rabbitmq internal authentication database. With a virtual host dedicated to the submissions, we can just set up three views on the django side to deal with all the judge authentication.

**Comment by quantum5** [comment] 2015-08-27 16:28
Basic RabbitMQ usage:

* One virtual host dedicated to this app (named in settings.py)
* One work queue (dispatch)
* Every judge has an anonymous queue to monitor for global notifications, like abort
* One exchange to route global notifications to all judges (broadcast)
* One queue to receive judge responses (response)
* All non-anonymous items gets created on app initialization

We can use a node.js server to provide ping time.

**Comment by quantum5** [comment] 2015-09-12 03:53
I think may be we actually need to have a test case counter too, considering we must eliminate the race of two handlers on the queue.

**Comment by quantum5** [comment] 2015-12-21 18:55
```pytb
Traceback (most recent call last):
  File "/code/site/judge/rabbitmq/daemon.py", line 65, in _handle_judge_response
    self._judge_response_handlers.get(packet['name'], self.on_malformed)(packet)
  File "/code/site/judge/rabbitmq/handler.py", line 182, in on_grading_end
    super(AMQPJudgeResponseDaemon, self).on_grading_end(packet)
  File "/code/site/judge/rabbitmq/daemon.py", line 97, in on_grading_end
    self._finish_submission(packet['id'])
  File "/code/site/judge/rabbitmq/daemon.py", line 56, in _finish_submission
    self.chan.basic_cancel(self._submission_tags[id])
  File "/code/pypy-virtenv/site-packages/pika/adapters/blocking_connection.py", line 1612, in basic_cancel
    lambda: consumer_tag not in self._impl._consumers)
  File "/code/pypy-virtenv/site-packages/pika/adapters/blocking_connection.py", line 1174, in _flush_output
    *waiters)
  File "/code/pypy-virtenv/site-packages/pika/adapters/blocking_connection.py", line 410, in _flush_output
    self._impl.ioloop.poll()
  File "/code/pypy-virtenv/site-packages/pika/adapters/select_connection.py", line 602, in poll
    self._process_fd_events(fd_event_map, write_only)
  File "/code/pypy-virtenv/site-packages/pika/adapters/select_connection.py", line 443, in _process_fd_events
    handler(fileno, events, write_only=write_only)
  File "/code/pypy-virtenv/site-packages/pika/adapters/base_connection.py", line 364, in _handle_events
    self._handle_read()
  File "/code/pypy-virtenv/site-packages/pika/adapters/base_connection.py", line 415, in _handle_read
    self._on_data_available(data)
  File "/code/pypy-virtenv/site-packages/pika/connection.py", line 1347, in _on_data_available
    self._process_frame(frame_value)
  File "/code/pypy-virtenv/site-packages/pika/connection.py", line 1427, in _process_frame
    self._deliver_frame_to_channel(frame_value)
  File "/code/pypy-virtenv/site-packages/pika/connection.py", line 1028, in _deliver_frame_to_channel
    return self._channels[value.channel_number]._handle_content_frame(value)
  File "/code/pypy-virtenv/site-packages/pika/channel.py", line 896, in _handle_content_frame
    self._on_deliver(*response)
  File "/code/pypy-virtenv/site-packages/pika/channel.py", line 975, in _on_deliver
    self.basic_reject(method_frame.method.delivery_tag)
  File "/code/pypy-virtenv/site-packages/pika/channel.py", line 394, in basic_reject
    raise TypeError('delivery_tag must be an integer')
TypeError: delivery_tag must be an integer
```

**Comment by quantum5** [comment] 2015-12-21 19:04
```pytb
Traceback (most recent call last):
  File "<builtin>/app_main.py", line 75, in run_toplevel
  File "/code/site/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/code/pypy-virtenv/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/code/pypy-virtenv/site-packages/django/core/management/__init__.py", line 342, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/code/pypy-virtenv/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/code/pypy-virtenv/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/code/site/judge/management/commands/runamqpd.py", line 9, in handle
    handler.run()
  File "/code/site/judge/rabbitmq/daemon.py", line 38, in run
    self.chan.start_consuming()
  File "/code/pypy-virtenv/site-packages/pika/adapters/blocking_connection.py", line 1681, in start_consuming
    self.connection.process_data_events(time_limit=None)
  File "/code/pypy-virtenv/site-packages/pika/adapters/blocking_connection.py", line 647, in process_data_events
    self._flush_output(common_terminator)
  File "/code/pypy-virtenv/site-packages/pika/adapters/blocking_connection.py", line 410, in _flush_output
    self._impl.ioloop.poll()
  File "/code/pypy-virtenv/site-packages/pika/adapters/select_connection.py", line 602, in poll
    self._process_fd_events(fd_event_map, write_only)
  File "/code/pypy-virtenv/site-packages/pika/adapters/select_connection.py", line 443, in _process_fd_events
    handler(fileno, events, write_only=write_only)
  File "/code/pypy-virtenv/site-packages/pika/adapters/base_connection.py", line 364, in _handle_events
    self._handle_read()
  File "/code/pypy-virtenv/site-packages/pika/adapters/base_connection.py", line 415, in _handle_read
    self._on_data_available(data)
  File "/code/pypy-virtenv/site-packages/pika/connection.py", line 1347, in _on_data_available
    self._process_frame(frame_value)
  File "/code/pypy-virtenv/site-packages/pika/connection.py", line 1427, in _process_frame
    self._deliver_frame_to_channel(frame_value)
  File "/code/pypy-virtenv/site-packages/pika/connection.py", line 1028, in _deliver_frame_to_channel
    return self._channels[value.channel_number]._handle_content_frame(value)
  File "/code/pypy-virtenv/site-packages/pika/channel.py", line 896, in _handle_content_frame
    self._on_deliver(*response)
  File "/code/pypy-virtenv/site-packages/pika/channel.py", line 983, in _on_deliver
    header_frame.properties, body)
  File "/code/pypy-virtenv/site-packages/pika/adapters/blocking_connection.py", line 1261, in _on_consumer_message_delivery
    consumer = self._consumer_infos[method.consumer_tag]
KeyError: 'ctag2.e460604405964a7987e578dce6d09772'
```

**Comment by Xyene** [comment] 2015-12-22 19:38
Sometimes the client waits for a very long time before acknowledging a submission.

```
INFO 2015-12-22 19:08:21,654 daemon Declare responsibility for: 156583: pid 9734
INFO 2015-12-22 19:08:21,662 dispatch Dispatching submission: 156583, language: MONOFS, code: helloworld
INFO 2015-12-22 19:08:38,397 packet Accept submission: 156583: executor: MONOFS, code: helloworld
INFO 2015-12-22 19:08:38,416 daemon Herculaneum: Submission acknowledged: 156583
```

I used `faulthandler` and obtained a thread dump that should be of some help:

```
Thread 0xb33ffb40 (most recent call first):
  File "/usr/lib/python2.7/threading.py", line 359 in wait
  File "/usr/lib/python2.7/threading.py", line 621 in wait
  File "/home/judge/judge/packet.py", line 270 in _ping_thread
  File "/usr/lib/python2.7/threading.py", line 763 in run
  File "/usr/lib/python2.7/threading.py", line 810 in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 783 in __bootstrap

Thread 0xb29ffb40 (most recent call first):
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/select_connection.py", line 590 in poll
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 410 in _flush_output
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 647 in process_data_events
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 1681 in start_consuming
  File "/usr/lib/python2.7/threading.py", line 763 in run
  File "/usr/lib/python2.7/threading.py", line 810 in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 783 in __bootstrap

Current thread 0xb7567700 (most recent call first):
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/select_connection.py", line 590 in poll
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 410 in _flush_output
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 647 in process_data_events
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 1788 in consume
  File "/home/judge/judge/packet.py", line 290 in _run
  File "/home/judge/judge/packet.py", line 436 in run
  File "/home/judge/judge/judge.py", line 330 in listen
  File "/home/judge/judge/judge.py", line 690 in main
  File "main.py", line 7 in <module>
```

**Comment by quantum5** [comment] 2015-12-24 19:52
RabbitMQ queue seems to be working perfectly. This issue will be closed once a judge is up for over a day.

**Comment by quantum5** [comment] 2015-12-25 01:24
Working fine.

**Closed by quantum5** 2015-12-25 01:24 UTC
Labels: discussion

**Comment by Xyene** [comment] 2015-12-25 12:58
Laputa did not survive staying online for a day.

```
  File "/usr/local/lib/python2.7/dist-packages/pika/channel.py", line 1150, in _send_method
    self.connection._send_method(self.channel_number, method_frame, content)
  File "/usr/local/lib/python2.7/dist-packages/pika/connection.py", line 1569, in _send_method
    self._send_frame(frame.Method(channel_number, method_frame))
  File "/usr/local/lib/python2.7/dist-packages/pika/connection.py", line 1548, in _send_frame
    raise exceptions.ConnectionClosed
pika.exceptions.ConnectionClosed
Exception in thread Thread-65:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/judge/judge/packet.py", line 271, in _ping_thread
    self.ping_packet()
  File "/home/judge/judge/packet.py", line 365, in ping_packet
    self._send_ping_packet(packet)
  File "/home/judge/judge/packet.py", line 343, in _send_ping_packet
    self.chan.basic_publish(exchange='', routing_key='judge-ping', body=json.dumps(packet).encode('zlib'))
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 1978, in basic_publish
    mandatory, immediate)
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/blocking_connection.py", line 2064, in publish
    immediate=immediate)
  File "/usr/local/lib/python2.7/dist-packages/pika/channel.py", line 338, in basic_publish
    (properties, body))
  File "/usr/local/lib/python2.7/dist-packages/pika/channel.py", line 1150, in _send_method
    self.connection._send_method(self.channel_number, method_frame, content)
  File "/usr/local/lib/python2.7/dist-packages/pika/connection.py", line 1571, in _send_method
    self._send_message(channel_number, method_frame, content)
  File "/usr/local/lib/python2.7/dist-packages/pika/connection.py", line 1601, in _send_message
    self._flush_outbound()
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/base_connection.py", line 282, in _flush_outbound
    self._handle_write()
  File "/usr/local/lib/python2.7/dist-packages/pika/adapters/base_connection.py", line 427, in _handle_write
    bw = self.socket.send(frame)
AttributeError: 'NoneType' object has no attribute 'send'
```

**Comment by quantum5** [comment] 2015-12-25 18:01
Perhaps it's because you didn't pull?

**Comment by quantum5** [comment] 2015-12-27 06:36
The upgrade to RabbitMQ `3.6.0` has proven that a RabbitMQ restart is not a disaster for judges, nor is it a problem for #184.

**Comment by quantum5** [comment] 2015-12-27 17:54
@Xyene how exactly do you feel about this?

```
PLAIN login refused: rabbit_auth_backend_http failed authenticating Laputa: {failed_connect,
                                                        [{to_address,
                                                          {"dmoj.ca",443}},
                                                         {inet,
                                                          [inet],
                                                          nxdomain}]}
```
